// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB77sPux7hmTZXTSqRkl8TjBp2jK_fttLM',
    appId: '1:462403554770:web:f18cffdaf0cd75e4a98c0b',
    messagingSenderId: '462403554770',
    projectId: 'my-flutter-firebase-proj-43967',
    authDomain: 'my-flutter-firebase-proj-43967.firebaseapp.com',
    storageBucket: 'my-flutter-firebase-proj-43967.appspot.com',
    measurementId: 'G-DL1DR3MS5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1p8VIpr5pWDI9MdnJwxHY51-kzo4rew',
    appId: '1:462403554770:android:b66ebfac5a3469a8a98c0b',
    messagingSenderId: '462403554770',
    projectId: 'my-flutter-firebase-proj-43967',
    storageBucket: 'my-flutter-firebase-proj-43967.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhNrYk4cQwUE3CbwgEA_qisz17Sv34rYI',
    appId: '1:462403554770:ios:0a43788dc9f00238a98c0b',
    messagingSenderId: '462403554770',
    projectId: 'my-flutter-firebase-proj-43967',
    storageBucket: 'my-flutter-firebase-proj-43967.appspot.com',
    iosBundleId: 'com.example.chetuTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhNrYk4cQwUE3CbwgEA_qisz17Sv34rYI',
    appId: '1:462403554770:ios:c342ce21d060fef9a98c0b',
    messagingSenderId: '462403554770',
    projectId: 'my-flutter-firebase-proj-43967',
    storageBucket: 'my-flutter-firebase-proj-43967.appspot.com',
    iosBundleId: 'com.example.chetuTraining.RunnerTests',
  );
}
